### PR TITLE
video-area: unbreak build with X11-less Gtk4

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by 02c1e86dae64. From [error log](https://github.com/celluloid-player/celluloid/files/7801826/celluloid-0.22.log):
```c
../src/celluloid-video-area.c:28:10: fatal error: 'gdk/x11/gdkx.h' file not found
#include <gdk/x11/gdkx.h>
         ^~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by jbeich** [comment]
FWIW, Celluloid works fine (runtime) in such a Wayland-only environment (no libX11 and others).

**Comment by gnome-mpv** [comment]
Merged as 5c47d53c86b8668a970ec4331468873fe7e0976b.

Thanks!
